// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SirJoshua.Web.Data;

#nullable disable

namespace SirJoshua.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616092942_AddLeadsAndEnquiries")]
    partial class AddLeadsAndEnquiries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SirJoshua.Web.Models.Ebook", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Badge")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("CompareAtIdr")
                        .HasColumnType("integer");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("IsBundle")
                        .HasColumnType("boolean");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<int>("PriceIdr")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric(2,1)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("Ebooks");

                    b.HasData(
                        new
                        {
                            Id = "band-7-formula",
                            Author = "Sir Joshua Academy",
                            Category = "IELTS",
                            CompareAtIdr = 599000,
                            Cover = "teal",
                            Description = "A structured guide to high-scoring IELTS Writing — Task 1 & 2 structures, Band 7+ vocabulary, sample responses and exam-day strategy.",
                            IsBundle = false,
                            Meta = "Digital guide · PDF",
                            PriceIdr = 399000,
                            Rating = 5.0m,
                            ReviewCount = 0,
                            Series = "IELTS · Writing",
                            SortOrder = 0,
                            Title = "IELTS Writing Mastery: The Band 7+ Formula"
                        },
                        new
                        {
                            Id = "writing-playbook",
                            Author = "Sir Joshua Academy",
                            Badge = "Best seller",
                            Category = "IELTS",
                            Cover = "teal",
                            Description = "Answer frameworks for Task 1 & 2 to stay consistent at band 7+.",
                            IsBundle = false,
                            Meta = "248 pp · PDF + EPUB",
                            PriceIdr = 149000,
                            Rating = 4.9m,
                            ReviewCount = 128,
                            Series = "IELTS · Writing",
                            SortOrder = 1,
                            Title = "The IELTS Writing Playbook"
                        },
                        new
                        {
                            Id = "speaking-fear",
                            Author = "Sir Joshua Academy",
                            Category = "IELTS",
                            Cover = "terra",
                            Description = "Fluency drills and natural sample answers for Speaking Parts 1–3.",
                            IsBundle = false,
                            Meta = "180 pp · PDF",
                            PriceIdr = 129000,
                            Rating = 4.8m,
                            ReviewCount = 96,
                            Series = "IELTS · Speaking",
                            SortOrder = 2,
                            Title = "Speaking Without Fear"
                        },
                        new
                        {
                            Id = "reading-speed",
                            Author = "Sir Joshua Academy",
                            Category = "IELTS",
                            Cover = "sand",
                            Description = "Skimming & scanning techniques to save time in the IELTS Reading test.",
                            IsBundle = false,
                            Meta = "132 pp · PDF",
                            PriceIdr = 89000,
                            Rating = 4.6m,
                            ReviewCount = 54,
                            Series = "IELTS · Reading",
                            SortOrder = 3,
                            Title = "Reading Speed & Skimming"
                        },
                        new
                        {
                            Id = "vocab-builder",
                            Author = "Sir Joshua Academy",
                            Badge = "Best seller",
                            Category = "General",
                            Cover = "gold",
                            Description = "The 1,200 most common academic words, complete with example sentences.",
                            IsBundle = false,
                            Meta = "210 pp · PDF + EPUB",
                            PriceIdr = 99000,
                            Rating = 4.9m,
                            ReviewCount = 203,
                            Series = "General · Vocabulary",
                            SortOrder = 4,
                            Title = "Academic Vocabulary Builder"
                        },
                        new
                        {
                            Id = "listening-focus",
                            Author = "Sir Joshua Academy",
                            Badge = "New",
                            Category = "IELTS",
                            Cover = "ink",
                            Description = "Prediction and note-taking techniques to lift your IELTS Listening score.",
                            IsBundle = false,
                            Meta = "150 pp · PDF",
                            PriceIdr = 99000,
                            Rating = 4.7m,
                            ReviewCount = 41,
                            Series = "IELTS · Listening",
                            SortOrder = 5,
                            Title = "Listening: Predict & Note"
                        },
                        new
                        {
                            Id = "grammar-essentials",
                            Author = "Sir Joshua Academy",
                            Category = "General",
                            Cover = "deep",
                            Description = "The grammar range and accuracy examiners reward — explained simply.",
                            IsBundle = false,
                            Meta = "176 pp · PDF",
                            PriceIdr = 109000,
                            Rating = 4.8m,
                            ReviewCount = 67,
                            Series = "General · Grammar",
                            SortOrder = 6,
                            Title = "Grammar Essentials for Band 7+"
                        },
                        new
                        {
                            Id = "bundle-band7",
                            Author = "Sir Joshua Academy",
                            Category = "Bundle",
                            CompareAtIdr = 674000,
                            Cover = "deep",
                            Description = "All the supporting IELTS practice guides in one bundle. Save versus buying separately.",
                            IsBundle = true,
                            Meta = "6 guides · PDF + EPUB",
                            PriceIdr = 499000,
                            Rating = 5.0m,
                            ReviewCount = 0,
                            Series = "Bundle · Practice",
                            SortOrder = 7,
                            Title = "Complete IELTS Practice Bundle"
                        });
                });

            modelBuilder.Entity("SirJoshua.Web.Models.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentBand")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("FocusArea")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("InterestType")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("PreferredDate")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("PreferredTime")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ProductOrServiceId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("SourcePage")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TargetBand")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TestDate")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ReferenceNumber");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("SirJoshua.Web.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountUsd")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("DiscountIdr")
                        .HasColumnType("integer");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayPalCaptureId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PayPalOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubtotalIdr")
                        .HasColumnType("integer");

                    b.Property<int>("TotalIdr")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("PayPalOrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SirJoshua.Web.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EbookId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("UnitPriceIdr")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SirJoshua.Web.Models.WritingFeedbackPackage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("RemainingCredits")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCredits")
                        .HasColumnType("integer");

                    b.Property<int>("UsedCredits")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceNumber");

                    b.ToTable("WritingFeedbackPackages");
                });

            modelBuilder.Entity("SirJoshua.Web.Models.WritingFeedbackSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("EstimatedBandScore")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("FeedbackNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("IeltsModule")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("ReferenceNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("integer");

                    b.Property<string>("TargetBand")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TaskType")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TestDate")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UploadedFileUrl")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<string>("WhatsApp")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("WritingText")
                        .HasMaxLength(12000)
                        .HasColumnType("character varying(12000)");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceNumber");

                    b.ToTable("WritingFeedbackSubmissions");
                });

            modelBuilder.Entity("SirJoshua.Web.Models.OrderItem", b =>
                {
                    b.HasOne("SirJoshua.Web.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SirJoshua.Web.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
