// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SirJoshua.Web.Data;

#nullable disable

namespace SirJoshua.Web.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SirJoshua.Web.Models.Ebook", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Badge")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("CompareAtIdr")
                        .HasColumnType("integer");

                    b.Property<string>("Cover")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<bool>("IsBundle")
                        .HasColumnType("boolean");

                    b.Property<string>("Meta")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<int>("PriceIdr")
                        .HasColumnType("integer");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric(2,1)");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<string>("Series")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("Ebooks");

                    b.HasData(
                        new
                        {
                            Id = "writing-playbook",
                            Author = "Aditya Pranata",
                            Badge = "Terlaris",
                            Category = "IELTS",
                            Cover = "teal",
                            Description = "Kerangka jawaban Task 1 & 2 untuk konsisten di band 7+.",
                            IsBundle = false,
                            Meta = "248 hal · PDF + EPUB",
                            PriceIdr = 149000,
                            Rating = 4.9m,
                            ReviewCount = 128,
                            Series = "IELTS · Writing",
                            SortOrder = 1,
                            Title = "The IELTS Writing Playbook"
                        },
                        new
                        {
                            Id = "speaking-fear",
                            Author = "Sarah Whitmore",
                            Category = "IELTS",
                            Cover = "terra",
                            Description = "Latihan fluency dan contoh jawaban Part 1–3 yang natural.",
                            IsBundle = false,
                            Meta = "180 hal · PDF",
                            PriceIdr = 129000,
                            Rating = 4.8m,
                            ReviewCount = 96,
                            Series = "IELTS · Speaking",
                            SortOrder = 2,
                            Title = "Speaking Without Fear"
                        },
                        new
                        {
                            Id = "toefl-integrated",
                            Author = "James O'Connor",
                            Badge = "Baru",
                            Category = "TOEFL",
                            Cover = "ink",
                            Description = "Strategi integrated tasks untuk reading, listening & speaking.",
                            IsBundle = false,
                            Meta = "312 hal · PDF + EPUB",
                            PriceIdr = 179000,
                            Rating = 4.7m,
                            ReviewCount = 74,
                            Series = "TOEFL · iBT",
                            SortOrder = 3,
                            Title = "TOEFL iBT: The Integrated Method"
                        },
                        new
                        {
                            Id = "pte-rapid",
                            Author = "Maya Setiawan",
                            Category = "PTE",
                            Cover = "deep",
                            Description = "Teknik menembus skor 79+ dengan format AI scoring PTE.",
                            IsBundle = false,
                            Meta = "156 hal · PDF",
                            PriceIdr = 139000,
                            Rating = 4.8m,
                            ReviewCount = 61,
                            Series = "PTE · Academic",
                            SortOrder = 4,
                            Title = "PTE Academic Rapid Score"
                        },
                        new
                        {
                            Id = "vocab-builder",
                            Author = "Tim Sir Joshua",
                            Badge = "Terlaris",
                            Category = "Umum",
                            Cover = "gold",
                            Description = "1.200 kata akademik tersering, lengkap dengan contoh kalimat.",
                            IsBundle = false,
                            Meta = "210 hal · PDF + EPUB",
                            PriceIdr = 99000,
                            Rating = 4.9m,
                            ReviewCount = 203,
                            Series = "Umum · Vocabulary",
                            SortOrder = 5,
                            Title = "Academic Vocabulary Builder"
                        },
                        new
                        {
                            Id = "reading-speed",
                            Author = "Aditya Pranata",
                            Category = "IELTS",
                            Cover = "sand",
                            Description = "Teknik skimming & scanning untuk hemat waktu di ujian.",
                            IsBundle = false,
                            Meta = "132 hal · PDF",
                            PriceIdr = 89000,
                            Rating = 4.6m,
                            ReviewCount = 54,
                            Series = "IELTS · Reading",
                            SortOrder = 6,
                            Title = "Reading Speed & Skimming"
                        },
                        new
                        {
                            Id = "bundle-band8",
                            Author = "Tim Sir Joshua",
                            Category = "Bundle",
                            CompareAtIdr = 784000,
                            Cover = "deep",
                            Description = "Semua panduan IELTS, TOEFL, PTE, dan vocabulary dalam satu paket. Hemat Rp 185.000 dibanding beli satuan.",
                            IsBundle = true,
                            Meta = "6 ebook · PDF + EPUB",
                            PriceIdr = 599000,
                            Rating = 5.0m,
                            ReviewCount = 0,
                            Series = "Bundle · Band 8",
                            SortOrder = 7,
                            Title = "Paket Lengkap Band 8"
                        });
                });

            modelBuilder.Entity("SirJoshua.Web.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AmountUsd")
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("DiscountIdr")
                        .HasColumnType("integer");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayPalCaptureId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PayPalOrderId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("SubtotalIdr")
                        .HasColumnType("integer");

                    b.Property<int>("TotalIdr")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("PayPalOrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SirJoshua.Web.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EbookId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<int>("UnitPriceIdr")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SirJoshua.Web.Models.OrderItem", b =>
                {
                    b.HasOne("SirJoshua.Web.Models.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SirJoshua.Web.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
